#!/bin/bash

input_folder="../input/GLDAS/GLDAS_VIC10_M/2002"

./shbaam_conc.py $input_folder/*.nc4 $input_folder/GLDAS_VIC10_M.A200204_200212.nc4

echo 
echo "Start testing concatenation"

cd ../tst
./test_conc.py 










